# Generated by Django 3.2.7 on 2021-09-14 08:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('saebyuk', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='thief',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
