# Generated by Django 3.2.7 on 2021-09-14 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('saebyuk', '0002_alter_book_thief'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='available',
            field=models.BooleanField(default=True, verbose_name='대출 가능 여부'),
        ),
    ]
